### ISSUE TITLE
妹が痔になったので座薬を入れてやった件运行不能

### ISSUE THREAD

**Issue by HarutoLiang** [zeas2/Kirikiroid2_patch#1]
试过在kirikiroid1.2.6和1.3.1下运行妹が痔になったので座薬を入れてやった件1.01
在没有打patch的情况下，有背景，无法显示立绘，到第一个Hsence会跳出
在打了patch之后，可以显示立绘，有背景，但无法显示CG
save和load会跳出，Qsave和Qload可以使用

**Comment by zeas2** [comment]
补丁已更新。
save和load会跳出的问题是模拟器自身的bug，在下一版本会修复。
补丁中已包含代码以兼容现有版本。

**Comment by chuanxi364** [comment]
依旧没有立绘啊
