### ISSUE TITLE
Tenioha! Girls Can Be Pervy Too!

### ISSUE THREAD

**Issue by Psyrosine** [zeas2/Kirikiroid2_patch#10]
VNDB page: https://vndb.org/v10326

Error occurs after hitting start in the main menu.

![screenshot_20180608-163948](https://user-images.githubusercontent.com/40076462/41185455-5038bcdc-6b3d-11e8-9b85-db6d0798a0b9.png)

**Comment by zeas2** [comment]
8e64d5189972fd30758704670f122f226cd31763
