### ISSUE TITLE
魔法使いの夜 一页文本即将结束的时候会fc

### ISSUE THREAD

**Issue by LoIIipop** [zeas2/Kirikiroid2_patch#2]
资源库下的高压版，打了之前在Google group上的补丁，1.2.6版本没问题，1.3.1版本会有这个问题

**Comment by LoIIipop** [comment]
补充一下，opengl, software都会fc

**Comment by zeas2** [comment]
感谢汇报bug，但这是模拟器的问题，应该提到https://github.com/zeas2/Kirikiroid2/issues
这里只提补丁相关的问题

你提的bug已处理，待模拟器更新
