### ISSUE TITLE
patch for new productions of poison soft

### ISSUE THREAD

**Issue by minhthangcb** [zeas2/Kirikiroid2_patch#20]
Finally lord zeas2 was revival !
I hope this is not momentarily because a lot of people need your help.
I'm here to need your help make patch for new productions of Poison soft:
https://vndb.org/v26054
https://vndb.org/v26547
https://vndb.org/v29189

**Comment by Akiraqvq** [comment]
Create a file named 'patch.tjs' and write:
```
Plugins.link("csvParser.dll");
Plugins.link("extrans.dll");
Plugins.link("fstat.dll");
Plugins.link("KAGParser.dll");
Plugins.link("kropus.dll");
Plugins.link("layerExImage.dll");
Plugins.link("wumsadp.dll");
Plugins.link("wuvorbis.dll");
function xp3SignCheck() {return true;}
function hotKeyHook() {}
```

Enjoy.

**Comment by minhthangcb** [comment]
Thanks you bro.
