### ISSUE TITLE
need update for 水蓮と紫苑

### ISSUE THREAD

**Issue by crownz-sec** [zeas2/Kirikiroid2_patch#22]
like the title

**Comment by zeas2** [comment]
e3ef15d687971a9ba472f017a48685c8d277e21f

**Comment by crownz-sec** [comment]
> [e3ef15d](https://github.com/zeas2/Kirikiroid2_patch/commit/e3ef15d687971a9ba472f017a48685c8d277e21f)

thanks~~

**Comment by crownz-sec** [comment]
> [e3ef15d](https://github.com/zeas2/Kirikiroid2_patch/commit/e3ef15d687971a9ba472f017a48685c8d277e21f)

I have used it, but seems doesn't work.
When I moved the xp3filter.tjs file to the home directory of the game and started the game with KRKR, it still showed that it could not convert byte characters to wide characters and some other errors.
