### ISSUE TITLE
水蓮と紫苑's patch seems doesn't work

### ISSUE THREAD

**Issue by crownz-sec** [zeas2/Kirikiroid2_patch#25]
When I moved the xp3filter.tjs file to the home directory of the game and started the game with KRKR, it still showed that it could not convert byte characters to wide characters and some other errors.

**Comment by crownz-sec** [comment]
This may be a problem with my resources, because when I switched to another resource and found that I could get into the game. But I haven't played yet, so I don't know if it will happen other problems later as others say.

**Comment by zinc213** [comment]
#26

**Comment by crownz-sec** [comment]
> #26

I noticed that, thank you.
